apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker
          image: bethanygrimm/exoplanet_api:1.0
          command: ["src/worker.py"]
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_IP
              value: "exoplanet-redis-service"
            - name: REDIS_PORT
              value: "6379"