apiVersion: v1
kind: Service
metadata:
  name: exoplanet-redis-service
spec:
  type: ClusterIP
  selector:
    app: exoplanet-redis
  ports:
    - name: exoplanet-redis
      port: 5000
      targetPort: 5000
